apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orchestrator.fullname" . }}
  labels: {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "orchestrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "orchestrator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: webserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.port }}
          env:
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
          volumeMounts:
            - name: secret-volume
              mountPath: /run/secrets
              readOnly: true
            - name: tmpfs-volume
              mountPath: /tmpfs
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["dagster-daemon", "run"]
          env:
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{- end }}
          volumeMounts:
            - name: secret-volume
              mountPath: /run/secrets
              readOnly: true
            - name: tmpfs-volume
              mountPath: /tmpfs
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Values.secretName }}
        - name: tmpfs-volume
          emptyDir:
            medium: Memory
