// flow-typed signature: c9aaac7bd11441ec4ff5e0ac882ae46a
// flow-typed version: <<STUB>>/@trpc/client_v^11.4.3/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@trpc/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@trpc/client' {
  declare module.exports: any;
}
