// flow-typed signature: 6b64cca7da478f50c5e677fba0b38b72
// flow-typed version: <<STUB>>/@trpc/client_v^11.4.3/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@trpc/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@trpc/client' {
  declare module.exports: any;
}
