// flow-typed signature: 581798ee7d51d31349841d16780a3c74
// flow-typed version: <<STUB>>/@trpc/react-query_v^11.4.3/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@trpc/react-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@trpc/react-query' {
  declare module.exports: any;
}
