// flow-typed signature: 1368f88d7f098d5c16775fc043c6f3fe
// flow-typed version: <<STUB>>/@auth0/nextjs-auth0_v4.8.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@auth0/nextjs-auth0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@auth0/nextjs-auth0' {
  declare module.exports: any;
}
