apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scoring-engine.fullname" . }}
  labels: {{- include "scoring-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "scoring-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "scoring-engine.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
