version: '3.8'
services:
  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres
    environment:
      POSTGRES_DB: app_test
  redis:
    extends:
      file: docker-compose.dev.yml
      service: redis
    environment:
      REDIS_DB: 1
  kafka:
    extends:
      file: docker-compose.dev.yml
      service: kafka
    environment:
      KAFKA_BROKER_ID: 99
