[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
extend-ignore = "E203,W503"
docstring-convention = "google"

[tool.mypy]
strict = true

[tool.docformatter]
wrap-summaries = 88
wrap-descriptions = 88

[mypy]
files = "backend"

