[tool.black]
target-version = ['py311']
line-length = 88

[tool.isort]
profile = 'black'

[tool.flake8]
max-line-length = 88
extend-ignore = ['E203', 'W503']

[tool.mypy]
python_version = 3.11
ignore_missing_imports = true

[tool.docformatter]
wrap-summaries = 79
wrap-descriptions = 79

[tool.pydocstyle]
convention = 'numpy'
