signal-ingestion:
  replicaCount: 1
  image:
    repository: example/signal-ingestion
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  env: {}
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

data-storage:
  replicaCount: 1
  image:
    repository: example/data-storage
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  env: {}
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

scoring-engine:
  replicaCount: 1
  image:
    repository: example/scoring-engine
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  env: {}
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

ai-mockup-generation:
  replicaCount: 1
  image:
    repository: example/ai-mockup-generation
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  env: {}
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

marketplace-publisher:
  replicaCount: 1
  image:
    repository: example/marketplace-publisher
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  env: {}
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

feedback-loop:
  replicaCount: 1
  image:
    repository: example/feedback-loop
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  env: {}
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

orchestrator:
  replicaCount: 1
  image:
    repository: example/orchestrator
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  env: {}
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

backup-jobs:
  image:
    repository: example/backup
    tag: latest
    pullPolicy: IfNotPresent
  schedule: "0 2 * * *"
  bucket: my-backup-bucket
  minioDataPath: /data
