// flow-typed signature: b598fbd40f68c944b8cf88c73551561b
// flow-typed version: <<STUB>>/@types/next-auth_v3.15.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/next-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/next-auth' {
  declare module.exports: any;
}
