// flow-typed signature: ccf29c50810c208edaf3fbcdce57c3da
// flow-typed version: <<STUB>>/@types/node_v24/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
