// flow-typed signature: 4021c962b3809411d1344d36978fc2f2
// flow-typed version: <<STUB>>/@types/react_v19/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
