apiVersion: v1
kind: Service
metadata:
  name: {{ include "marketplace-publisher.fullname" . }}
  labels: {{- include "marketplace-publisher.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "marketplace-publisher.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
