// flow-typed signature: 66b9e82f7ea6894a073e2a64948803b6
// flow-typed version: <<STUB>>/autoprefixer_v10.4.21/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autoprefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'autoprefixer' {
  declare module.exports: any;
}
