// flow-typed signature: 33a7c3fb091461e9cf22f648aa344268
// flow-typed version: <<STUB>>/babel-jest_v30.0.4/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-jest' {
  declare module.exports: any;
}
