// flow-typed signature: c766901dfc07dc17e0d4f14276a42406
// flow-typed version: <<STUB>>/chart.js_v4.5.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chart.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chart.js' {
  declare module.exports: any;
}
