// flow-typed signature: 7ae2068006f7ae1976dfd09d1011bce7
// flow-typed version: <<STUB>>/eslint-plugin-import_v^2.32.0/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-import' {
  declare module.exports: any;
}
