// flow-typed signature: 0bbd5734c43d11ef8dd07af1db02475b
// flow-typed version: <<STUB>>/eslint-config-prettier_v^10.1.5/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}
