// flow-typed signature: 8ce01cfb9f328c6986c89f24d7c24747
// flow-typed version: <<STUB>>/eslint-plugin-n_v^17.21.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-n' {
  declare module.exports: any;
}
