// flow-typed signature: 8b7e490772eec0aaec752bcef47653c6
// flow-typed version: <<STUB>>/eslint-plugin-promise_v^7.2.1/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-promise' {
  declare module.exports: any;
}
