// flow-typed signature: f52a5b0ff5582f1ec372080ab3e01ca2
// flow-typed version: <<STUB>>/eslint-plugin-react_v^7.37.5/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
