// flow-typed signature: d459d84cb6aad2c7c8ff1868414c75b0
// flow-typed version: <<STUB>>/eslint-plugin-n_v^17.21.0/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-n' {
  declare module.exports: any;
}
