// flow-typed signature: 23663ab94a90113387c8e09b2fb37c06
// flow-typed version: <<STUB>>/eslint-config-standard_v^17.1.0/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-standard' {
  declare module.exports: any;
}
