// flow-typed signature: 0284f33e3081dbdc5958fd8f10be8c80
// flow-typed version: <<STUB>>/eslint-plugin-jsx-a11y_v^6.10.2/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jsx-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jsx-a11y' {
  declare module.exports: any;
}
