// flow-typed signature: 44ab593b1b4264bd799e6267f8a3242b
// flow-typed version: <<STUB>>/eslint-config-prettier_v^10.1.8/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}
