// flow-typed signature: dc877a9966e5b0f68ed72a40abaad0c7
// flow-typed version: <<STUB>>/eslint-config-next_v^15.4.3/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-next' {
  declare module.exports: any;
}
