// flow-typed signature: 4cfb20811d3fd0546099c1b87765f154
// flow-typed version: <<STUB>>/eslint-plugin-promise_v^7.2.1/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-promise' {
  declare module.exports: any;
}
