// flow-typed signature: 09e0e3ba50b412c9cc8bf53f4f912a70
// flow-typed version: <<STUB>>/eslint-plugin-react_v^7.37.5/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
