// flow-typed signature: b08b56abd6d7ff2701a34a9fde832b0c
// flow-typed version: <<STUB>>/eslint-config-next_v^15.4.1/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-next' {
  declare module.exports: any;
}
