// flow-typed signature: 73bd07fe07fc358d47072148ed1bdd60
// flow-typed version: <<STUB>>/eslint_v^9.31.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
