// flow-typed signature: 1dabe38db2d7b33c4276c4886d16e7d2
// flow-typed version: <<STUB>>/flow-bin_v0.276.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-bin' {
  declare module.exports: any;
}
