// flow-typed signature: bfccb0d24f3dac2a99e344dc216f3181
// flow-typed version: <<STUB>>/jest_v30.0.4/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest' {
  declare module.exports: any;
}
