// flow-typed signature: 577850a7b35d214b1bb4ef797d598cab
// flow-typed version: <<STUB>>/jest-canvas-mock_v2.5.2/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-canvas-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-canvas-mock' {
  declare module.exports: any;
}
