// flow-typed signature: eb051b7e58f8376073130c52437776ff
// flow-typed version: <<STUB>>/jest-environment-jsdom_v30.0.4/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-jsdom' {
  declare module.exports: any;
}
