// flow-typed signature: 81f91c49d68f73cab20a13f945f7e1b2
// flow-typed version: <<STUB>>/next-router-mock_v1.0.2/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-router-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-router-mock' {
  declare module.exports: any;
}
