// flow-typed signature: 0d67e5a3d21e303af4ccf30f5a1a2b47
// flow-typed version: <<STUB>>/next_v15.4.1/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next' {
  declare module.exports: any;
}
