// flow-typed signature: 28e3e53b3eb817365b5fd85318fbbffa
// flow-typed version: <<STUB>>/next-pwa_v5.6.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-pwa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-pwa' {
  declare module.exports: any;
}
