// flow-typed signature: 9bb34ec962bbb581f60d779f1622a6e6
// flow-typed version: <<STUB>>/next-auth_v4.24.11/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-auth' {
  declare module.exports: any;
}
