// flow-typed signature: c9c6c73b20dce474c6029a0a803b9c0f
// flow-typed version: <<STUB>>/postcss_v8.5.6/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss' {
  declare module.exports: any;
}
