// flow-typed signature: 6b337db4ae74f758eee605c47132920d
// flow-typed version: <<STUB>>/prettier_v^3.6.2/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
