// flow-typed signature: 64a47296a2dfb93a81be5ea8f0a7d189
// flow-typed version: <<STUB>>/prettier_v^3.6.2/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
