// flow-typed signature: 92c5d920d8160121f5f28c64554acf57
// flow-typed version: <<STUB>>/react-chartjs-2_v5.3.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-chartjs-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-chartjs-2' {
  declare module.exports: any;
}
