// flow-typed signature: 2c917f716ab04a45039572fe54d2cb31
// flow-typed version: <<STUB>>/react-dom_v19.1.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom' {
  declare module.exports: any;
}
