// flow-typed signature: 5859a536f95e09c1607ea49eef04ce9d
// flow-typed version: <<STUB>>/stylelint_v^16.21.1/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}
