// flow-typed signature: b2f043223828446fedd00a50a71311bb
// flow-typed version: <<STUB>>/stylelint-config-standard_v^38.0.0/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-standard' {
  declare module.exports: any;
}
