// flow-typed signature: 735c28914277eba6285030c99de5d192
// flow-typed version: <<STUB>>/stylelint_v^16.22.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}
