// flow-typed signature: eb201f1f45a8bfaec636d5c54634d064
// flow-typed version: <<STUB>>/stylelint-config-css-modules_v^4.5.1/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-css-modules/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-css-modules/dist/index' {
  declare module.exports: $Exports<'stylelint-config-css-modules/dist'>;
}
declare module 'stylelint-config-css-modules/dist/index.js' {
  declare module.exports: $Exports<'stylelint-config-css-modules/dist'>;
}
