// flow-typed signature: 87ca8cf9804ef4aace1044daff5b5d88
// flow-typed version: <<STUB>>/stylelint-config-tailwindcss_v^1.0.0/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-tailwindcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-tailwindcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-config-tailwindcss/scss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-config-tailwindcss/index' {
  declare module.exports: $Exports<'stylelint-config-tailwindcss'>;
}
declare module 'stylelint-config-tailwindcss/index.js' {
  declare module.exports: $Exports<'stylelint-config-tailwindcss'>;
}
declare module 'stylelint-config-tailwindcss/scss.js' {
  declare module.exports: $Exports<'stylelint-config-tailwindcss/scss'>;
}
