// flow-typed signature: 4886cc9063ae6e11b539243e64a20387
// flow-typed version: <<STUB>>/stylelint-config-css-modules_v^4.5.1/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-css-modules' {
  declare module.exports: any;
}
