// flow-typed signature: 0be1d62f34c4c98d7f1c4ab6cc06da7e
// flow-typed version: <<STUB>>/stylelint-config-tailwindcss_v^1.0.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-tailwindcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-tailwindcss' {
  declare module.exports: any;
}
