// flow-typed signature: cfd24a6d1270eda31fd5669ed89ba55a
// flow-typed version: <<STUB>>/tailwindcss_v4.1.11/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tailwindcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tailwindcss' {
  declare module.exports: any;
}
