// flow-typed signature: 43f8e2e3506c0cc112f5d39cc7ace72d
// flow-typed version: <<STUB>>/typescript_v^5.8.3/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript' {
  declare module.exports: any;
}
