// flow-typed signature: af530115d5380b440748342834045b1e
// flow-typed version: <<STUB>>/@axe-core/playwright_v^4.10.2/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@axe-core/playwright'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@axe-core/playwright' {
  declare module.exports: any;
}
