// flow-typed signature: 34d9c9a5b1ae6883148a4af81974f09c
// flow-typed version: <<STUB>>/@axe-core/playwright_v^4.10.2/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@axe-core/playwright'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@axe-core/playwright' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@axe-core/playwright/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@axe-core/playwright/dist/index' {
  declare module.exports: $Exports<'@axe-core/playwright/dist'>;
}
declare module '@axe-core/playwright/dist/index.js' {
  declare module.exports: $Exports<'@axe-core/playwright/dist'>;
}
