// flow-typed signature: 8436f2a2010e34ce2e318b3779328ba8
// flow-typed version: <<STUB>>/@babel/preset-env_v7.28.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-env' {
  declare module.exports: any;
}
