// flow-typed signature: 3c32921c34317dd92f9e1cbf27ff00c8
// flow-typed version: <<STUB>>/@babel/preset-typescript_v7.27.1/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-typescript' {
  declare module.exports: any;
}
