// flow-typed signature: 1ed8f4a3e5832021b427c63cae79246a
// flow-typed version: <<STUB>>/@babel/preset-react_v7.27.1/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-react' {
  declare module.exports: any;
}
