// flow-typed signature: 0dcbb0e40d834e0a4a7fa512a7b93acb
// flow-typed version: <<STUB>>/@eslint/eslintrc_v^3.3.1/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eslint/eslintrc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eslint/eslintrc' {
  declare module.exports: any;
}
