// flow-typed signature: 41b1310ca84ba332eab0868d050a142c
// flow-typed version: <<STUB>>/@eslint/js_v^9.31.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eslint/js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eslint/js' {
  declare module.exports: any;
}
