// flow-typed signature: 8b3f3be3f1f0446f3cb79271eb65c483
// flow-typed version: <<STUB>>/@eslint/js_v^9.31.0/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eslint/js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eslint/js' {
  declare module.exports: any;
}
