// flow-typed signature: b61e920ed268aa25c20354b0562c9371
// flow-typed version: <<STUB>>/@playwright/test_v^1.54.1/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@playwright/test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@playwright/test' {
  declare module.exports: any;
}
