// flow-typed signature: 40cf0055e964e3938d98dd1ba937d53f
// flow-typed version: <<STUB>>/@playwright/test_v^1.54.1/flow_v0.275.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@playwright/test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@playwright/test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@playwright/test/cli' {
  declare module.exports: any;
}

declare module '@playwright/test/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module '@playwright/test/cli.js' {
  declare module.exports: $Exports<'@playwright/test/cli'>;
}
declare module '@playwright/test/index' {
  declare module.exports: $Exports<'@playwright/test'>;
}
declare module '@playwright/test/index.js' {
  declare module.exports: $Exports<'@playwright/test'>;
}
declare module '@playwright/test/reporter.js' {
  declare module.exports: $Exports<'@playwright/test/reporter'>;
}
