apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-mockup-generation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-mockup-generation
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: External
      external:
        metric:
          name: celery_queue_length
        target:
          type: AverageValue
          averageValue: "30"
