apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-mockup-generation
  labels:
    app: ai-mockup-generation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-mockup-generation
  template:
    metadata:
      labels:
        app: ai-mockup-generation
    spec:
      containers:
        - name: ai-mockup-generation
          image: example/ai-mockup-generation:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: LOKI_URL
              value: http://loki:3100
          envFrom:
            - configMapRef:
                name: shared-config
            - secretRef:
                name: shared-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
