apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  endpoints:
    - path: /metrics
      targetPort: 80
      interval: 30s
