resources:
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - api-gateway-servicemonitor.yaml
  - marketplace-publisher-deployment.yaml
  - marketplace-publisher-service.yaml
  - marketplace-publisher-servicemonitor.yaml
  - signal-ingestion-deployment.yaml
  - signal-ingestion-service.yaml
  - signal-ingestion-servicemonitor.yaml
  - scoring-engine-deployment.yaml
  - scoring-engine-service.yaml
  - scoring-engine-servicemonitor.yaml
  - analytics-deployment.yaml
  - analytics-service.yaml
  - analytics-servicemonitor.yaml
  - ai-mockup-generation-deployment.yaml
  - ai-mockup-generation-service.yaml
  - ai-mockup-generation-servicemonitor.yaml
  - ai-mockup-generation-hpa.yaml
  - feedback-loop-deployment.yaml
  - feedback-loop-service.yaml
  - feedback-loop-servicemonitor.yaml
  - optimization-deployment.yaml
  - optimization-service.yaml
  - optimization-servicemonitor.yaml
  - monitoring-deployment.yaml
  - monitoring-service.yaml
  - monitoring-servicemonitor.yaml
  - configmap.yaml
  - secret.yaml
  - loki-deployment.yaml
  - loki-service.yaml
  - cronjobs/orchestrator-backup.yaml
  - cronjobs/orchestrator-cleanup.yaml
  - cronjobs/orchestrator-idea.yaml
  - cronjobs/orchestrator-query-plan.yaml
