apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: marketplace-publisher
  labels:
    app: marketplace-publisher
spec:
  selector:
    matchLabels:
      app: marketplace-publisher
  endpoints:
    - path: /metrics
      targetPort: 80
      interval: 30s
