apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: optimization
  labels:
    app: optimization
spec:
  selector:
    matchLabels:
      app: optimization
  endpoints:
    - path: /metrics
      targetPort: 80
      interval: 30s
