apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  endpoints:
    - path: /metrics
      targetPort: 80
      interval: 30s
