apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "monitoring.fullname" . }}
  labels: {{- include "monitoring.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "monitoring.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: /metrics
      targetPort: {{ .Values.service.port }}
      interval: 30s
