apiVersion: v1
kind: Service
metadata:
  name: {{ include "feedback-loop.fullname" . }}
  labels: {{- include "feedback-loop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "feedback-loop.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
