// flow-typed signature: 97242c26c8b58bd07abed874503281ba
// flow-typed version: <<STUB>>/@testing-library/jest-dom_v6.6.3/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/jest-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/jest-dom' {
  declare module.exports: any;
}
