// flow-typed signature: e0b122b0bef227da5b591863dc13e595
// flow-typed version: <<STUB>>/@testing-library/react_v16.3.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/react' {
  declare module.exports: any;
}
