// flow-typed signature: 7eba91542d41a94919c5826018b0d80e
// flow-typed version: <<STUB>>/@testing-library/user-event_v14.6.1/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/user-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/user-event' {
  declare module.exports: any;
}
