apiVersion: batch/v1
kind: CronJob
metadata:
  name: orchestrator-query-plan
spec:
  schedule: "30 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: orchestrator
              image: example/orchestrator:latest
              imagePullPolicy: IfNotPresent
              command: ["dagster", "job", "execute", "-m", "orchestrator.jobs", "-j", "analyze_query_plans_job"]
