// flow-typed signature: cca0968b6c670b2bb163129cd22685ce
// flow-typed version: <<STUB>>/@tanstack/react-query_v5.83.0/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tanstack/react-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tanstack/react-query' {
  declare module.exports: any;
}
