redbubble:
  max_file_size_mb: 10
  max_width: 8000
  max_height: 8000
  upload_limit: 50
amazon_merch:
  max_file_size_mb: 25
  max_width: 15000
  max_height: 15000
  upload_limit: 100
etsy:
  max_file_size_mb: 20
  max_width: 10000
  max_height: 10000
  upload_limit: 80
shopify:
  max_file_size_mb: 20
  max_width: 10000
  max_height: 10000
  upload_limit: 80
