scrape_configs:
  - job_name: 'monitoring'
    static_configs:
      - targets: ['monitoring:8000']
  - job_name: 'services'
    static_configs:
      - targets:
          - 'api-gateway:8000'
          - 'analytics:8000'
          - 'optimization:8000'
          - 'service-template:8000'
          - 'signal-ingestion:8000'
          - 'feedback-loop:8000'
          - 'marketplace-publisher:8000'
          - 'mockup-generation:8000'
          - 'scoring-engine:5002'
