scrape_configs:
  - job_name: 'monitoring'
    static_configs:
      - targets: ['monitoring:8000']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
  - job_name: 'mockup-generation'
    static_configs:
      - targets: ['mockup-generation:8000']
  - job_name: 'scoring-engine'
    static_configs:
      - targets: ['scoring-engine:5002']
  - job_name: 'marketplace-publisher'
    static_configs:
      - targets: ['marketplace-publisher:8000']
  - job_name: 'signal-ingestion'
    static_configs:
      - targets: ['signal-ingestion:8000']
  - job_name: 'feedback-loop'
    static_configs:
      - targets: ['feedback-loop:8000']
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:3000']
