// flow-typed signature: 5c5067f6309525feeafe937e48330d8c
// flow-typed version: <<STUB>>/@tailwindcss/postcss_v4/flow_v0.276.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tailwindcss/postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tailwindcss/postcss' {
  declare module.exports: any;
}
