apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics.fullname" . }}
  labels: {{- include "analytics.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "{{ .Values.service.port }}"
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "analytics.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
