replicaCount: 1
image:
  repository: example/feedback-loop
  tag: staging
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources: {}

# Environment variables
env: {}

# Horizontal pod autoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70
