apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mockup-generation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mockup-generation
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: celery_queue_length
          selector:
            matchLabels:
              queue: gpu
        target:
          type: AverageValue
          averageValue: "3"
