name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          npm ci
          python -m pip install -e .
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Generate OpenAPI specs
        run: python scripts/generate_openapi.py
      - name: Run linting
        run: make lint
      - name: Run Flow
        run: npm run flow
      - name: Run MyPy
        run: mypy backend --explicit-package-bases --exclude "tests" --strict --config-file backend/mypy.ini
      - name: Run tests
        run: make test

  docker:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build images
        run: make docker-build
      - name: Push images
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          TAG: ${{ github.sha }}
        run: make docker-push REGISTRY=$REGISTRY TAG=$TAG

  deploy:
    needs: docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.12.3'
      - name: Deploy to cluster
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          TAG: ${{ github.sha }}
          ENV: prod
        run: make helm-deploy REGISTRY=$REGISTRY TAG=$TAG ENV=$ENV
