name: Docker

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-${{ github.sha }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: desainz:latest
      - name: Scan image
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          image-ref: desainz:latest
          format: table
          exit-code: 1
