name: Docker Build and Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver-opts: image=moby/buildkit:latest
      - name: Build mockup-generation image
        uses: docker/build-push-action@v5
        with:
          context: backend/mockup-generation
          tags: mockup-generation:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build orchestrator image
        uses: docker/build-push-action@v5
        with:
          context: backend/orchestrator
          tags: orchestrator:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: mockup-generation:latest
          severity: CRITICAL,HIGH
          exit-code: 1
      - name: Scan orchestrator image with Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: orchestrator:latest
          severity: CRITICAL,HIGH
          exit-code: 1
      - name: Smoke test core services
        run: ./scripts/smoke_compose.sh
