name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          npm ci
      - name: Run Black
        run: black --check .
      - name: Run Flake8
        run: flake8 .
      - name: Run MyPy
        run: mypy backend --explicit-package-bases --exclude "tests"
      - name: Run ESLint/Prettier/Stylelint
        run: npm run lint
      - name: Run CSS lint
        run: npm run lint:css
      - name: Run Flow
        run: npm run flow
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'
      - name: Lint Helm charts
        run: |
          for chart in infrastructure/helm/*/Chart.yaml; do
            helm lint "$(dirname "$chart")"
          done
