name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHONWARNINGS: "error"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Black check
        run: black --check src tests
      - name: Flake8
        run: flake8 src tests
      - name: Mypy
        run: mypy --strict src
      - name: Docformatter check
        run: docformatter --check --recursive src
      - name: Pydocstyle
        run: pydocstyle src
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Node deps
        run: npm install
      - name: Prettier check
        run: npx prettier --check "js/**/*.js"
      - name: ESLint
        run: npx eslint js --max-warnings=0
      - name: Stylelint
        run: npx stylelint styles.css --max-warnings=0
