name: Nightly Benchmarks

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      PYTHONWARNINGS: error
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          python -m pip install -e .
      - name: Benchmark scoring
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/benchmark_score.py --persist
      - name: Benchmark mockup generation
        run: python scripts/benchmark_mockup.py --prompt "test" --runs 1

