name: OWASP ZAP Scan

on:
  push:
    branches: [main]

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://staging.example.com'
          fail_action: false
          cmd_options: '-J zap_report.json'
      - name: Fail if medium or high vulnerabilities found
        run: |
          if jq '.site[].alerts[] | select((.riskcode|tonumber) >= 2)' zap_report.json | grep -q .; then
            echo "Medium or high vulnerabilities detected."
            exit 1
          fi

