name: OWASP ZAP Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend dependencies
        run: |
          npm ci --prefix frontend/admin-dashboard
      - name: Build and start app
        run: |
          npm run build --prefix frontend/admin-dashboard
          npm start --prefix frontend/admin-dashboard &
          sleep 15
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:3000'
          fail_action: true
      - name: Stop server
        run: |
          kill $(lsof -t -i:3000) || true
