name: Release Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build images
        run: make docker-build
      - name: Push images
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          TAG: ${{ github.ref_name }}
        run: make docker-push REGISTRY=$REGISTRY TAG=$TAG
