name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONWARNINGS: "error"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests
        run: pytest -W error
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install Node deps
        run: npm install
      - name: Run Node tests
        run: npm test
